; DO NOT REMOVE THIS LINE. It's a checking.
(defun c:1() (princ "\nSDIP: ") (c:SDIP))
(defun c:2() (princ "\nINT: ") (c:INT))
(defun c:3() (princ "\nSDIPP: ") (c:SDIPP))
(defun c:4() (princ "\nRoadOffsetForDrainage: ") (DT:RoadOffsetForDrainage))
(defun DT:RoadOffsetForDrainage( / p ent_name )
  ; Select a polyline within an Xref, and offset it by 0.5m and 1m either side
  (c:N)
  ; Check if groups exists
  (setq ent_name (entlast) )
  (vla-offset (vlax-ename->vla-object ent_name) 0.5)
  (command "_groupedit" "N" "road_offsets" "A" (entlast) "")
  (vla-offset (vlax-ename->vla-object ent_name) 1)
  (command "_groupedit" "N" "road_offsets" "A" (entlast) "")
  (vla-offset (vlax-ename->vla-object ent_name) -0.5)
  (command "_groupedit" "N" "road_offsets" "A" (entlast) "")
  (vla-offset (vlax-ename->vla-object ent_name) -1)
  (command "_groupedit" "N" "road_offsets" "A" (entlast) "")
  (vla-delete (vlax-ename->vla-object ent_name))
  (princ)
)
